### ISSUE TITLE
Regarding some terms

### ISSUE THREAD

**Issue by Sahil1776** [gideon-ogunbanjo/FeelFlare#1]
Thank you creating such a nice app. I tried it and it worked wonderfully. 

I was playing around with it and I tried to confuse it. So it started predicting 'Neutral'. Then I added 'hahahaha' and it still predicted 'Neutral'. After that, I removed 'hahahaha' and replaced it with 'that's funny'. Then it predicted 'Positive'. 
This can be used to improve the model even further. Let me know if you need help in this, I'd happy to contribute. 
Thank you

**Comment by gideon-ogunbanjo** [comment]
Thank you for your positive feedback! I'd love for you to contribute to the app. Feel free to share any ideas or examples you have in mind to further improve the model. Your input is highly appreciated!

**Comment by adityaa1205** [comment]
Hello sir ! 
can you please help me with this project . as i am having some doubts like the output will we on browser or google collab only ?
